### PR TITLE
[#3105] Remove iocpreactor support.

### PR DESCRIPTION
**Pull request by alibotean**
## Problem

We want to automate the Python distribution for Windows. We do not support source compilation and we do not use the `iocpreactor`.
## Changes
- [x] Remove the `iocpreactor` support from Twisted,
- [x] Change versioning scheme to use only digits as `pip` does not handle alphanumeric parts correctly.
## How to test

Please check that changes make sense.

### CODE REVIEW

**Comment by alibotean** [comment]
I have not released the new version, and don't plant to do so until there's is an approval. I've done my tests using `.1` and `.2` as internal versions.

needs-review

**Comment by adiroiban** [comment]
Thanks.

why remove the code?

why not just remove the part from setup.py or twisted/python/dist.py which tried to build the iocprector extension?

I don't see the 5 why section. Why we need this? We used to have this package before and we had no problem with iocpreactor :)

needs-changes

**Comment by alibotean** [comment]
> I don't see the 5 why section. Why we need this? We used to have this package before and we had no problem with iocpreactor :)

Just tried and it works as is (no iocpreactor removal) if I use the proper versioning scheme.

What do you think? Should I just fix the version or also remove the extension from `dist.py` ?

**Comment by alibotean** [comment]
needs-review

**Comment by alibotean** [comment]
Now I have no idea why when using the manually created distribution this does not happen, I will do a clean and deps again and peruse the pip logs to see what's going on.

**Comment by adiroiban** [comment]
just fix the version. I don't like that we do such big changes in upstream version.

Thanks!

needs-changes

**Comment by alibotean** [comment]
I give up trying to figure out why it behaves differently when running `deps` with the manually built distribution.

I've tried using `--log` argument for `pip` but the critical part, averything after installing brink is not logged even if I use `silent=False`.

I've made the automated dist "look" like the manual one (removed all the extra folders) and it still downloading Twisted 15.xxx instead of keeping the already existing one.

---

I will roll back all my changes and keep only the version. The package is already released.

**Pull request closed without merging**
